services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
      - keycloak-data:/opt/keycloak/data # Para persistir datos do Keycloak no volume criado
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  caixaverso-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/quarkus-app
    volumes:
      - sqlite-data:/work/data # Persistir os datos do Sqlite
    depends_on:
      - keycloak
    restart: on-failure

volumes:
  sqlite-data:
  keycloak-data: